---
title: "Mission preparation"
subtitle: Protocols/resources for preparing a glider for a mission
---

*This page is under construction and feedback is very welcome! Hit "Report an issue" on the right to provide suggestions.*

Clickable/editable Google Doc version - [Mission Prep Task List - TEMPLATE](https://docs.google.com/document/d/1TMXsop5GJW_rMxrP8zSuazALNi_j8nHq24RIIzfw7_A/edit?tab=t.0#heading=h.7xtkyk82v1ni). Suggest making a copy of this template for each glider/mission to track tasks and take notes. 

**Main categories of prep steps:**  
    *\*(this page currently covers the items with a check)*

- [Hardware checks](#hardware-checks)
  - &#x2713; Ballast or tank test
  - &#x2713; Update mass in `sg_calib_constants.m` 
  - work record updates
- [Mission planning](#mission-planning)
  - &#x2713; Set up Shared Drive folders
  - &#x2713; Set up local folders
  - track/endurance planning
  - shipping
- [Basestation prep](#prepare-basestation)
  - &#x2713; Update constants (`sg_calib_constants.m`, `sg_plot_constants.m`)
  - &#x2713; Initiate new mission
  - &#x2713; Add mission to `mission.yml`
  - Check/prep piloting files
- Launch day prep
  - Self test review
  - Parameter checks
  - Final file checks
- ??

---

# Hardware checks

- [ ] Complete refurbishment and bench tests of any new sensors (tracked in [work records](https://drive.google.com/drive/u/0/folders/1Jcx4QQY_ujkqmqNBxfgTCHX-VeUrRU9r))

### Ballast or tank test 

After a refurbishment or any new sensors have been installed, ballast (if major mass/volume changes) or tank test (if minor changes) to get preliminary/approximate trim centers and check glider buoyancy for the planned mission conditions. 

See [Tank Ballasting Procedure](https://docs.google.com/document/d/1Sx_tv-fnL69xdCXWQwYgJ5MQdmun7sLenrywtFPlwvY/edit?tab=t.0#heading=h.2m0cz7fh78at) for a detailed guide of the operational steps (main menu guidance, etc.) to check centers and buoyancy in a tank.

- [ ] Use [Tank test and Ballast Calculations](https://docs.google.com/document/d/1b6X5l-R-8e2ALiu8q5KYue_S4rOvQ0H3Nii5-_5S7o0/edit?usp=drive_link) to run some calculations on the values collected with the above procedure to confirm that the observed buoyancy and trim centers are appropriate for the planned mission.
- [ ] Update [Work Record](https://docs.google.com/spreadsheets/d/1YsNtV8qwVBUALXFxBaR8tk-P6ZU2w9QV4eZkyafvf_s/edit?gid=0#gid=0) with relevant info
- [ ] Update [Inventory Tracker](https://docs.google.com/spreadsheets/d/1dORG6XC6ikm7x13q_PeKNE1b6C-R49zsDDRrlINzBvM/edit?gid=15308096#gid=15308096) if any major sensor changes were made

### Update checkout sheet

::: {.callout-important}
The checkout sheet is the guide to each glider build and contains all the details needed to set up a glider mission so it's critical to keep it updated!
:::

A new checkout sheet is needed following any work - refurbishments, repairs, sensor installations, or ballasting - with the new mass and any other relevant info such as sensor serial numbers or calibration dates

- [ ] Create a new checkout sheet
  - Make a copy of the existing doc and rename with today's date
  - Update the relevant fields with the correct value, any important notes, and the date it was updated

Check sheets are stored in the glider-specific folders in the [NMFS PIC Gliders Shared Drive](https://drive.google.com/drive/u/0/folders/0ADBCQZl7LcMGUk9PVA). 

```default
NMFS PIC Gliders
├── SG273
└── SG274
  ├── sg274 checkout sheet YYYY-MM-DD.xlsx
  └── sg274 checkout sheet YYYY-MM-DD.xlsx
```

### If shipping...  

- [ ] Complete and review a pre-shipment self test (either run this with the refurbishment mission or with the upcoming mission set on the basestation)
- [ ] Review final packing list and pack crates


<sub>[Back to top](#)</sub>

# Mission planning

## Logistics
- [ ] Draft survey plans
- [ ] Make final track (generate map and summary info, generate targets vfile, generate CSV of planned survey at 5 km resolution for Navy)
- [ ] Draft deployment plan/float plan
- [ ] Arrange shipping (pickup, storage on arrival, hazmat paperwork)
- [ ] Draft pilot schedule


## Set up local and cloud file structure

Set up folder structure for this mission following the [PIFSC Glider Data Management Plan](https://docs.google.com/document/d/1FCwBSUFHXaw8124u0K0YmNmUrCakKbkyKyzvz7sumNM/edit?tab=t.0#heading=h.78r6l01m6htp). Mission planning and documentation (not related to the basestation) will be stored here. 

### Create a mission folder on Google Drive

In the [NMFS PIC Gliders Shared Drive](https://drive.google.com/drive/u/0/folders/0ADBCQZl7LcMGUk9PVA), navigate to the 'missions' folder and create a new folder named with the mission title. Follow the below structure to create the relevant folders and documents. Template files for a pilot log, pilot schedule, and mission report are available in the main 'missions' folder. 

This folder structure is still underdevelopment (we have to see how some projects and missions go to assess what is working or not working!) so the organization at the start of a mission is not critical or set in stone. However, we do want all relevant parts to be created and stored generally together before the mission begins. 

For example, we are still working out how to organize things when more than one glider is flown for a project - each glider has it's own organizational string (e.g., `sgxxx_YYYYMMDD_location`, pilot log, and configuration files) but that project would likely have a single pilot schedule and report.

```default
YYYYMMDD_location/project
│   mission report
├── photos
│   pilot log
│   pilot schedule
└── prep
    ├── acoustic configuration
    │   ballasting worksheet
    │   check sheet
    └── tracks
```

See the ['missions' folder section](https://docs.google.com/document/d/1FCwBSUFHXaw8124u0K0YmNmUrCakKbkyKyzvz7sumNM/edit?tab=t.0#heading=h.78r6l01m6htp) for full details. 

### OPTIONAL: Create a local mission folder

If you'll be processing files mid-mission with __*agate*__ it's helpful to set up that local folder structure. 

- Create a 'mission' folder on the desktop or somewhere else easily accessible for downloading any glider basestation or piloting files locally. Suggest naming by the glider and mission name *e.g.*, `sgxxx_YYYYMMDD_location` to match the conventions used in __*agate*__
- Either manually create the  `basestationFiles` and `flightStatus` folders within this mission folder, or use `mkdir` in MATLAB to create them

### OPTIONAL: Setup __*agate*__

- Check for any updates to __*agate*__ from GitHub ([https://github.com/sfregosi/agate](https://github.com/sfregosi/agate)), if desired
- Set up a configuration file for this glider and mission
- Create a download script for easy downloading of basestation files to the local machine and generating some summary stats for the mission
- See __*agate*__ documentation for more detail on these steps



<sub>[Back to top](#)</sub>

# Prepare basestation

*These instructions are for seaglider.pub/basestation3*

- Connect to `seaglider.pub` via terminal (see [Command Line Guide](https://docs.google.com/document/d/1Kb-Txhg0VRp1Su7b27i2SznoJHQzJHwh0H2XGFuCZoE) for help with the command line)
- Navigate to the glider's home directory `/home/jails/noaaosu/gliderjail/home/SGxxx`
- All piloting files from the last mission should be in a mission-specific folder (named with `YYYYMMDD_location`) that is also mapped as the current folder
   - Check the current folder with the command `ls -la` from the home directory. This will display all files with details and the current folder will be listed with `->` with the folder it is currently mapped to
- If there are mission-specific piloting files (e.g. `baselog`, `p######.log`, `.nc`, etc.) those need to be moved using `MoveData.py` (this is unlikely as it was the old approach) BEFORE setting up the new mission or they may be overwritten

::: {.callout-caution collapse="true"}

##### Old mission files need to be moved with `MoveData.py`

*(only if `NewMission.py` was NOT used to set up the previous mission)*

- Navigate to the glider’s home directory *e.g.*, `/home/jails/noaaosu/gliderjail/home/SGxxx` or the folder with the files to be moved
- Run `basepy MoveData.py -m <currentLocation> -t <newLocation>`
   - `<currentLocation>` is the location of the files to be moved. Use `.` if you are in the home directory. Alternatively it can be specified as the full path to `/home/jails/noaaosu/gliderjail/home/sgxxx` (the glider's home directory) or a different folder
   - `<newLocation>` should be `YYYY-MM-DD_deployment_location` or if it is just sim dives to be moved, `YYYY-MM_DD_sim_dives`. Path only has to be specified relative to the present working directory 
  
**NOTE:** I think this script **does not** move wispr files (`ws0001az.x00`, etc) and so those must be moved manually
:::

## Create the new mission directory

- Navigate to the glider’s home directory *e.g.*, `/home/jails/noaaosu/gliderjail/home/sgXXX`
- Use `NewMission.py` to create a new folder for this specific mission
   - The function will set up the mapping of the `current` folder so all newly created piloting files will be saved here when the glider calls in
   - It will copy or make shortcuts to required piloting files like `pagers.yml`, `cmdfile`, `sg_calib_constants.m`, and `sg_plot_constants.m`. 
- Run the function with the below code
  - `<newMissionFolderName>` is the folder name that matches the mission title string set in `sg_calib_constants.m` and follows the format of `YYYYMMDD_location/project` where location/project is something like `Oahu` or `WHICEAS`
      - Example: `20251202_tests_wispr`

```default
basepy NewMission.py ./ <newMissionFolderName>

# note the above uses seaglider.pub's shortcut to map full python paths
# alternatively could use full paths
/opt/basestation/bin/python /usr/local/basestation3/NewMission.py ./ <newMissionFolderName>
``` 
- Check that it was set up properly by running `ls -la` from the home directory

::: {.callout-caution collapse="true"}

##### What files get copied from where??
- `sg_calib_constants.m`,  `sg_plot_constants.m`, `sections.yml`, `cmdfile`, `targets`, `science`, `scicon.sh` get copied from previous mission (if it exists) or the home directory. These will need further checking/updating (below)
- It will create a shortcut to `pagers.yml` and other dot configuration files (in the glider's home diretory)
- It will create a blank database file `sgxxx.db`
:::


## Add the mission to `missions.yml`

Update the `missions.yml` file to properly display this mission as a tile and linked page on the seaglider.pub site (vis).

The syntax is very specific and errors can be difficult to debug so it is best practice to create a backup copy before making any changes
- Navigate to your user folder (`/home/jails/noaaosu/username`) and use `cp ../gliderjail/home/missions.yml missions.orig` to create a backup of the existing `missions.yml` in your user directory 

- Navigate to `/home/jails/noaaosu/gliderjail/home` 
- Open `missions.yml` for editing (using vi or nano)
- Copy the previous mission to the `# past missions` section if needed
  - Mark the previous mission as complete by adding the line `status: complete`
- Update the mission name and folder path in the `# current missions` section

Example syntax *(note the below examples use the OSU naming scheme)*
  
```default
# long form
  - 
    glider: 273
    mission: 20251202_tests_wispr
    path: sg273/20251202_tests_wispr
    
# condensed
  - { glider: 273, mission: 20251202_tests_wispr, path: sg273/20251202_tests_wispr, status: complete}
```

- If anything isn't working, start over from the original by copying it over from your user directory:
```default
# from the home directory
cp ../../username/missions.orig missions.yml

# from your user directory
cp missions.orig ../gliderjail/home/missions.yml
```

## Update "constants" files

These two files exist/have copies in the glider's home folder and the latest version will be copied to the mission folder when it is created below, so update them in the home directory first. 

### Update `sg_calib_constants.m`

- [ ] Update mission title, and any mass or calibration changes from refurbishment or repairs
   - Modify the copy of `sg_calib_constants.m` in the current (newly created) mission folder
   - Update the "Last updated" line at the top with today's date and your initials
   - For record keeping, make a copy in the glider's home folder (`/gliderjail/home/sgXXX` ) but rename to include the date modified (e.g., `sg_calib_constants_2025-08-28.m`)
   ```default
   # from the glider's current folder
   cp sg_calib_constants.m ../sg_calib_constants_YYYY-MM-DD.m
   ```
### Update `sg_plot_constants.m`

- [ ] Update latitude/longitude bounds for the map shown on the mission tile on seaglider.pub
  - The home directory may have some examples for common locations (e.g., Shilshole) that can be copied or new coordinates can be entered


<sub>[Back to top](#)</sub>


# Launch day tasks

### Prep and upload final piloting files

Review the below files and upload them to the current mission folder. These can either be edited directly via the command line (using either `vi` or `nano` editors if using `seaglider.pub`) or by downloading and re-uploading manually using WinSCP. See the [Command Line Guide](https://docs.google.com/document/d/1Kb-Txhg0VRp1Su7b27i2SznoJHQzJHwh0H2XGFuCZoE) for help with the command line. 

- `sg_calib_constants.m`
  - Change mission name and mass and update any calibration coefficients
  - If not using basestation3, also update `rho0`, `volmax` and the hydrodynamic parameters
- `sg_plot_constants.m`
  - Set vis map figure lat/lon extents
- Upload `cmdfile`
  - Check all params and update where needed for first short dive
- Check/update `science` (note format varies slightly for v66.12 or v67.0 gliders)
- Upload `targets`
  - For help creating a targets file, see the [Mission planning](https://sfregosi.github.io/agate/mission-planning.html) page of the __*agate*__ documentation
- Check `pmar.cnf` (if PMAR system only)
- Check/update `pagers.yml` (basestation3) or `.pagers` (OSU basestation)
- Check/update any `pdoscmds.bat` or create placeholders
  - Shouldn't need one to start a mission but sometimes is useful to have a placeholder such as `pdoscmds.bat_target` that is loaded and ready to be copied/modified as needed. Examples of these can be stored in your user directory and copied into the specific glider's mission folder
  
<sub>[Back to top](#)</sub>



*More to come soon...*

- [Mission Prep Task List - TEMPLATE](https://docs.google.com/document/d/1TMXsop5GJW_rMxrP8zSuazALNi_j8nHq24RIIzfw7_A/edit?tab=t.0#heading=h.7xtkyk82v1ni)


